/**
 * Sidebar untuk dokumen legal
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebarsLegal = {
  legalSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebarsLegal;
