/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  guidelineSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Scan seluruh isi dari folder docs-guideline/
    },
  ],
};
